### ISSUE TITLE
Need to specify CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1 in proxy.php with 1.9.5500 and old php 7.4?

### ISSUE THREAD

**Issue by simbus82** [akunzai/MageBridgeCore#70]
Same problem of many years ago. Joomla (v3) is not receiving any data from magento/openmage (v19) with Magebridge 1.9.x
Tonight a magebrige 1.9.5500 with php 7.4 stop to work.
After some research, i remebered this
https://github.com/simbus82/MageBridgeCore/commit/f95b3fb794563523e6064ff27f00b390ed13e18d

So i tried a lot and... i put this for a test: 
CURLOPT_HTTP_VERSION         => **CURL_HTTP_VERSION_1_1**,

Now all is working!

Probably our server this night has received an update. The CURL version in this moment is 8.7.1. I don't know if it is changed just this night!

**Comment by akunzai** [comment]
Hi @simbus82,

Rather than compile CURL 8.7.1 and PHP 7.4, I decide to make the CURL HTTP Version configurable at next 1.9.6100 release

Please try [1.9.6100-beta](https://github.com/akunzai/MageBridgeCore/releases/tag/1.9.6100-beta) in your non-production environment.

It would be great to hear your good news soon.

![CURL HTTP Version](https://github.com/akunzai/MageBridgeCore/assets/574719/d9d122ad-3c75-4165-9080-32073353ec6c)

**Comment by simbus82** [comment]
Wow,
Thanks a lot, this is a great improvement!
I will try asap.

**Comment by simbus82** [comment]
Hi @akunzai, I think the declarations of the values of the variable that goes in the proxy.php file are missing, could it be?
![image](https://github.com/akunzai/MageBridgeCore/assets/1375730/9dddf250-97bb-4de4-9fca-7a74af753f55)

**Comment by akunzai** [comment]
Hi @simbus82 the value should be injected into proxy.php at line 443
 https://github.com/akunzai/MageBridgeCore/blob/84b7f9c292fbb85755faaf33905cfc63693f9963/joomla/components/com_magebridge/models/proxy.php#L443

the enum value was defined at https://github.com/curl/curl/blob/master/include/curl/curl.h#L2266

**Comment by simbus82** [comment]
Sorry for the late check, it's all working great! Thanks @akunzai!
